services:
  app:
    entrypoint:
      - sleep
      - infinity
    image:  docker pull ghcr.io/mentasuave01/deno-devcontainer:2.0.0
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
